# path to TensorFlow Object Detection API frozen inference graph
inference_graph_pepper: /home/jele/catkin_ws/src/ros_object_detector/frozen_inference_graph_frcnn.pb
inference_graph_leaf: /home/jele/catkin_ws/src/ros_object_detector/frozen_inference_graph_leaf.pb
# path to TensorFlow Object Detection API label map
label_map_pepper: /home/jele/catkin_ws/src/ros_object_detector/labelmap_frcnn.pbtxt
label_map_leaf: /home/jele/catkin_ws/src/ros_object_detector/labelmap_leaf.pbtxt
# confidence level to report objects as detected
ssd_confidence: 0.3

image_topic: /color/image_raw
point_cloud_topic: /depth_registered/points
camera_frame: camera
base_frame: world
