# confidence level to report objects as detected
ssd_confidence: 0.75

image_topic: /camera/color/image_raw
point_cloud_topic: /camera/depth/points
camera_frame: panda_camera_link_optical
base_frame: world
